[tool.poetry]
name = "light-puck"
version = "0.1.0"
description = ""
authors = ["Ricardo Matsui"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
bluepy = "*"
datadog = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
