---

- name: systemd reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: ingress_systemd_reload

- name: restart ingress vpn host sync timer
  ansible.builtin.systemd:
    daemon_reload: true
    name: vpn-host-sync.timer
    state: restarted
  listen: ingress_vpn_host_sync_restart

- name: restart ingress service
  ansible.builtin.systemd:
    daemon_reload: true
    name: ingress
    state: restarted
  listen: ingress_service_restart

- name: restart nftables
  ansible.builtin.reboot:
  listen: ingress_nftables_restart
