---

- name: restart scheduler service
  ansible.builtin.systemd:
    daemon_reload: true
    name: scheduler.timer
    state: restarted
  listen: scheduler_service_restart

- name: restart scheduler restart service
  ansible.builtin.systemd:
    daemon_reload: true
    name: scheduler-restart.timer
    state: restarted
  listen: scheduler_restart_service_restart
